/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check


/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
//    tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually

  tutorialSidebar: [
    'welcome',
    'architecture',
    {
        type: 'category',
        label: 'Getting Started',
        link: {type: 'doc', id: 'gettingStarted/main'},
        items: [
                'gettingStarted/system-requirements',
                'gettingStarted/installation',
                {
                    type: 'category', 
                    label: 'Configuration',
                    link: {type: 'doc', id: 'gettingStarted/configuration'},
                    items: [{type: 'autogenerated', dirName: 'configuration'},],
//                    items: ['configuration/users', 'configuration/assets', 'configuration/materials', 'configuration/modes', 'configuration/states'],
                },
        ],
    },
//    {type: 'link', label: 'KanoaOPS', href: 'https://kanoa.ai/kanoa-ops'},

    {
        type: 'category',
        label: 'Operations Management',
        link: {type: 'doc', id: 'kanoa-ops'},
        items: [{type: 'autogenerated', dirName: 'kanoa-ops'},],
    },
    {
        type: 'category',
        label: 'Quality Management',
        link: {type: 'doc', id: 'kanoa-quality'},
        items: [{type: 'autogenerated', dirName: 'kanoa-quality'},],
    },
    {
        type: 'category',
        label: 'Operations Analysis',
        link: {type: 'doc', id: 'kanoa-ops-analysis'},
        items: [{type: 'autogenerated', dirName: 'kanoa-ops-analysis'},],
    },
    {
        type: 'category',
        label: 'Appendix - API',
        link: {type: 'doc', id: 'api-intro'},
//        items: [{type: 'autogenerated', dirName: 'APPENDIX/System Functions/system.kanoa'},],
        items: [
            {type: 'category', label: 'system.kanoa.asset', link: {type: 'doc', id: 'systemFunctions/apiAssetIntro'},
                items: [
                            {type: 'doc', id: 'systemFunctions/asset/addAsset', label: 'addAsset'},
                            {type: 'doc', id: 'systemFunctions/asset/addAssetAttribute', label: 'addAssetAttribute'},
                            {type: 'doc', id: 'systemFunctions/asset/addAssetGroup', label: 'addAssetGroup'},
                            {type: 'doc', id: 'systemFunctions/asset/addAssetTagUDTInstance', label: 'addAssetTagUDTInstance'},
                            {type: 'doc', id: 'systemFunctions/asset/addAssetType', label: 'addAssetType'},
                            {type: 'doc', id: 'systemFunctions/asset/addCounter', label: 'addCounter'},
                            {type: 'doc', id: 'systemFunctions/asset/addCounterType', label: 'addCounterType'},
                            {type: 'doc', id: 'systemFunctions/asset/addMode', label: 'addMode'},
                            {type: 'doc', id: 'systemFunctions/asset/addState', label: 'addState'},
                            {type: 'doc', id: 'systemFunctions/asset/addStateCategory', label: 'addStateCategory'},
                            {type: 'doc', id: 'systemFunctions/asset/adjustTimeForSite', label: 'adjustTimeForSite'},
                            {type: 'doc', id: 'systemFunctions/asset/copyAsset', label: 'copyAsset'},
                            {type: 'doc', id: 'systemFunctions/asset/deleteAssetAttribute', label: 'deleteAssetAttribute'},
                            {type: 'doc', id: 'systemFunctions/asset/deleteAssetGroup', label: 'deleteAssetGroup'},
                            {type: 'doc', id: 'systemFunctions/asset/deleteAssets', label: 'deleteAssets'},
                            {type: 'doc', id: 'systemFunctions/asset/deleteAssetsWithForce', label: 'deleteAssetsWithForce'},
                            {type: 'doc', id: 'systemFunctions/asset/deleteAssetTagStructure', label: 'deleteAssetTagStructure'},
                            {type: 'doc', id: 'systemFunctions/asset/deleteAssetType', label: 'deleteAssetType'},
                            {type: 'doc', id: 'systemFunctions/asset/deleteCounter', label: 'deleteCounter'},
                            {type: 'doc', id: 'systemFunctions/asset/deleteCounterType', label: 'deleteCounterType'},
                            {type: 'doc', id: 'systemFunctions/asset/deleteMode', label: 'deleteMode'},
                            {type: 'doc', id: 'systemFunctions/asset/deleteState', label: 'deleteState'},
                            {type: 'doc', id: 'systemFunctions/asset/deleteStateCategory', label: 'deleteStateCategory'},
                            {type: 'doc', id: 'systemFunctions/asset/editAssetGroup', label: 'editAssetGroup'},
                            {type: 'doc', id: 'systemFunctions/asset/enableAssetStateLink', label: 'enableAssetStateLink'},
                            {type: 'doc', id: 'systemFunctions/asset/enableMode', label: 'enableMode'},
                            {type: 'doc', id: 'systemFunctions/asset/enableModeAssetLink', label: 'enableModeAssetLink'},
                            {type: 'doc', id: 'systemFunctions/asset/getAssetAttributes', label: 'getAssetAttributes'},
                            {type: 'doc', id: 'systemFunctions/asset/getAssetGroups', label: 'getAssetGroups'},
                            {type: 'doc', id: 'systemFunctions/asset/getAssetModes', label: 'getAssetModes'},
                            {type: 'doc', id: 'systemFunctions/asset/getAssets', label: 'getAssets'},
                            {type: 'doc', id: 'systemFunctions/asset/getAssetStates', label: 'getAssetStates'},
                            {type: 'doc', id: 'systemFunctions/asset/getAssetTagPath', label: 'getAssetTagPath'},
                            {type: 'doc', id: 'systemFunctions/asset/getAssetTypes', label: 'getAssetTypes'},
                            {type: 'doc', id: 'systemFunctions/asset/getCounter', label: 'getCounter'},
                            {type: 'doc', id: 'systemFunctions/asset/getCounterType', label: 'getCounterType'},
                            {type: 'doc', id: 'systemFunctions/asset/getCurrentModeInfo', label: 'getCurrentModeInfo'},
                            {type: 'doc', id: 'systemFunctions/asset/getCurrentStateInfo', label: 'getCurrentStateInfo'},
                            {type: 'doc', id: 'systemFunctions/asset/getModes', label: 'getModes'},
                            {type: 'doc', id: 'systemFunctions/asset/getModeSourceId', label: 'getModeSourceId'},
                            {type: 'doc', id: 'systemFunctions/asset/getModeTypes', label: 'getModeTypes'},
                            {type: 'doc', id: 'systemFunctions/asset/getOperationalAssets', label: 'getOperationalAssets'},
                            {type: 'doc', id: 'systemFunctions/asset/getParentAsset', label: 'getParentAsset'},
                            {type: 'doc', id: 'systemFunctions/asset/getSiteTimezoneOffset', label: 'getSiteTimezoneOffset'},
                            {type: 'doc', id: 'systemFunctions/asset/getStateCategory', label: 'getStateCategory'},
                            {type: 'doc', id: 'systemFunctions/asset/getStates', label: 'getStates'},
                            {type: 'doc', id: 'systemFunctions/asset/getStateType', label: 'getStateType'},
                            {type: 'doc', id: 'systemFunctions/asset/linkAssetModes', label: 'linkAssetModes'},
                            {type: 'doc', id: 'systemFunctions/asset/linkAssetStates', label: 'linkAssetStates'},
                            {type: 'doc', id: 'systemFunctions/asset/setAssetModeCode', label: 'setAssetModeCode'},
                            {type: 'doc', id: 'systemFunctions/asset/setAssetStateLinkCode', label: 'setAssetStateLinkCode'},
                            {type: 'doc', id: 'systemFunctions/asset/unlinkAssetMode', label: 'unlinkAssetMode'},
                            {type: 'doc', id: 'systemFunctions/asset/unlinkAssetState', label: 'unlinkAssetState'},
                            {type: 'doc', id: 'systemFunctions/asset/updateAsset', label: 'updateAsset'},
                            {type: 'doc', id: 'systemFunctions/asset/updateAssetModeField', label: 'updateAssetModeField'},
                            {type: 'doc', id: 'systemFunctions/asset/updateAssetType', label: 'updateAssetType'},
                            {type: 'doc', id: 'systemFunctions/asset/updateCounter', label: 'updateCounter'},
                            {type: 'doc', id: 'systemFunctions/asset/updateMode', label: 'updateMode'},
                            {type: 'doc', id: 'systemFunctions/asset/updateState', label: 'updateState'},
                            {type: 'doc', id: 'systemFunctions/asset/updateStateCategory', label: 'updateStateCategory'},
                            {type: 'doc', id: 'systemFunctions/asset/updateStateField', label: 'updateStateField'},
                        ]
            },
            {type: 'category', label: 'system.kanoa.attribute', link: {type: 'doc', id: 'systemFunctions/apiAttributeIntro'},
                items: [
                            {type: 'doc', id: 'systemFunctions/attribute/addAttribute', label: 'addAttribute'},
                            {type: 'doc', id: 'systemFunctions/attribute/addAttributeAssetLink', label: 'addAttributeAssetLink'},
                            {type: 'doc', id: 'systemFunctions/attribute/addAttributeEvent', label: 'addAttributeEvent'},
                            {type: 'doc', id: 'systemFunctions/attribute/deleteAttribute', label: 'deleteAttribute'},
                            {type: 'doc', id: 'systemFunctions/attribute/deleteAttributeAssetLink', label: 'deleteAttributeAssetLink'},
                            {type: 'doc', id: 'systemFunctions/attribute/deleteAttributeEvent', label: 'deleteAttributeEvent'},
                            {type: 'doc', id: 'systemFunctions/attribute/deleteAttributeWithHistory', label: 'deleteAttributeWithHistory'},
                            {type: 'doc', id: 'systemFunctions/attribute/getAttributeAssetLinks', label: 'getAttributeAssetLinks'},
                            {type: 'doc', id: 'systemFunctions/attribute/getAttributeEvents', label: 'getAttributeEvents'},
                            {type: 'doc', id: 'systemFunctions/attribute/getAttributes', label: 'getAttributes'},
                            {type: 'doc', id: 'systemFunctions/attribute/updateAttribute', label: 'updateAttribute'},
                            {type: 'doc', id: 'systemFunctions/attribute/updateAttributeAssetLink', label: 'updateAttributeAssetLink'},
                            {type: 'doc', id: 'systemFunctions/attribute/updateAttributeEvent', label: 'updateAttributeEvent'},
                        ]
            },
            {type: 'category', label: 'system.kanoa.config', link: {type: 'doc', id: 'systemFunctions/apiConfigIntro'},
                items: [
                            {type: 'doc', id: 'systemFunctions/config/getBackgroundColor', label: 'getBackgroundColor'},
                            {type: 'doc', id: 'systemFunctions/config/getConfig', label: 'getConfig'},
                            {type: 'doc', id: 'systemFunctions/config/getDBName', label: 'getDBName'},
                            {type: 'doc', id: 'systemFunctions/config/getTagProvider', label: 'getTagProvider'},
                            {type: 'doc', id: 'systemFunctions/config/getVersionInfo', label: 'getVersionInfo'},
                            {type: 'doc', id: 'systemFunctions/config/populateMenu', label: 'populateMenu'},
                            {type: 'doc', id: 'systemFunctions/config/updateVersionInfo', label: 'updateVersionInfo'},
                            {type: 'doc', id: 'systemFunctions/config/writeConfig', label: 'writeConfig'},
                        ]
            },
            {type: 'category', label: 'system.kanoa.date', link: {type: 'doc', id: 'systemFunctions/apiDateIntro'},
                items: [
                            {type: 'doc', id: 'systemFunctions/date/getClientOffsetMinsFromGateway', label: 'getClientOffsetMinsFromGateway'},
                            {type: 'doc', id: 'systemFunctions/date/getDateRange', label: 'getDateRange'},
                       ]
            },
            {type: 'category', label: 'system.kanoa.event', link: {type: 'doc', id: 'systemFunctions/apiEventIntro'},
                items: [
                            {type: 'doc', id: 'systemFunctions/event/addCountEvent', label: 'addCountEvent'},
                            {type: 'doc', id: 'systemFunctions/event/addModeEvent', label: 'addModeEvent'},
                            {type: 'doc', id: 'systemFunctions/event/addStateEvent', label: 'addStateEvent'},
                            {type: 'doc', id: 'systemFunctions/event/assetOperationChange', label: 'assetOperationChange'},
                            {type: 'doc', id: 'systemFunctions/event/buildDowntimeBarChartByDay', label: 'buildDowntimeBarChartByDay'},
                            {type: 'doc', id: 'systemFunctions/event/buildProductionBarChartByDay', label: 'buildProductionBarChartByDay'},
                            {type: 'doc', id: 'systemFunctions/event/checkforDuplicateModeEvents', label: 'checkforDuplicateModeEvents'},
                            {type: 'doc', id: 'systemFunctions/event/checkItemInfo', label: 'checkItemInfo'},
                            {type: 'doc', id: 'systemFunctions/event/clearZeroedCountEvents', label: 'clearZeroedCountEvents'},
                            {type: 'doc', id: 'systemFunctions/event/deleteCountEvent', label: 'deleteCountEvent'},
                            {type: 'doc', id: 'systemFunctions/event/deleteCountEvent', label: 'deleteCountEvents'},
                            {type: 'doc', id: 'systemFunctions/event/deleteModeEvent', label: 'deleteModeEvent'},
                            {type: 'doc', id: 'systemFunctions/event/deleteStateEvent', label: 'deleteStateEvent'},
                            {type: 'doc', id: 'systemFunctions/event/getCountEvent', label: 'getCountEvent'},
                            {type: 'doc', id: 'systemFunctions/event/getCountTotal', label: 'getCountTotal'},
                            {type: 'doc', id: 'systemFunctions/event/getDowntimeData', label: 'getDowntimeData'},
                            {type: 'doc', id: 'systemFunctions/event/getDowntimeDataByCategory', label: 'getDowntimeDataByCategory'},
                            {type: 'doc', id: 'systemFunctions/event/getDowntimeDataByInterval', label: 'getDowntimeDataByInterval'},
                            {type: 'doc', id: 'systemFunctions/event/getDowntimeDataByShift', label: 'getDowntimeDataByShift'},
                            {type: 'doc', id: 'systemFunctions/event/getDowntimeDataByShiftSummary', label: 'getDowntimeDataByShiftSummary'},
                            {type: 'doc', id: 'systemFunctions/event/getDowntimeDataForReliability', label: 'getDowntimeDataForReliability'},
                            {type: 'doc', id: 'systemFunctions/event/getDowntimeDataSummary', label: 'getDowntimeDataSummary'},
                            {type: 'doc', id: 'systemFunctions/event/getModeEvents', label: 'getModeEvents'},
                            {type: 'doc', id: 'systemFunctions/event/getOEEColors', label: 'getOEEColors'},
                            {type: 'doc', id: 'systemFunctions/event/getOEEDataByInterval', label: 'getOEEDataByInterval'},
                            {type: 'doc', id: 'systemFunctions/event/getOEEDataByIntervalByShift', label: 'getOEEDataByIntervalByShift'},
                            {type: 'doc', id: 'systemFunctions/event/getOEEDataSummary', label: 'getOEEDataSummary'},
                            {type: 'doc', id: 'systemFunctions/event/getPreviousModeEvent', label: 'getPreviousModeEvent'},
                            {type: 'doc', id: 'systemFunctions/event/getPreviousStateEvent', label: 'getPreviousStateEvent'},
                            {type: 'doc', id: 'systemFunctions/event/getProductionEvents', label: 'getProductionEvents'},
                            {type: 'doc', id: 'systemFunctions/event/getProductionEventsByShift', label: 'getProductionEventsByShift'},
                            {type: 'doc', id: 'systemFunctions/event/getProductionEventsForReliability', label: 'getProductionEventsForReliability'},
                            {type: 'doc', id: 'systemFunctions/event/getProductionEventSummary', label: 'getProductionEventSummary'},
                            {type: 'doc', id: 'systemFunctions/event/getStateEventById', label: 'getStateEventById'},
                            {type: 'doc', id: 'systemFunctions/event/getStateEventInfo', label: 'getStateEventInfo'},
                            {type: 'doc', id: 'systemFunctions/event/getStateEvents', label: 'getStateEvents'},
                            {type: 'doc', id: 'systemFunctions/event/getStateEventSummary', label: 'getStateEventSummary'},
                            {type: 'doc', id: 'systemFunctions/event/resetCountEvents', label: 'resetCountEvents'},
                            {type: 'doc', id: 'systemFunctions/event/updateCountEvent', label: 'updateCountEvent'},
                            {type: 'doc', id: 'systemFunctions/event/updateModeEvent', label: 'updateModeEvent'},
                            {type: 'doc', id: 'systemFunctions/event/updateStateEvent', label: 'updateStateEvent'},
                            {type: 'doc', id: 'systemFunctions/event/updateStateEventInfo', label: 'updateStateEventInfo'},
                            {type: 'doc', id: 'systemFunctions/event/updateWorkOrderCount', label: 'updateWorkOrderCount'},
                        ]
            },
            {type: 'category', label: 'system.kanoa.item', link: {type: 'doc', id: 'systemFunctions/apiItemIntro'},
                items: [
                            {type: 'doc', id: 'systemFunctions/item/addItem', label: 'addItem'},
                            {type: 'doc', id: 'systemFunctions/item/addItemAssetRate', label: 'addItemAssetRate'},
                            {type: 'doc', id: 'systemFunctions/item/addItemAttribute', label: 'addItemAttribute'},
                            {type: 'doc', id: 'systemFunctions/item/addItemClass', label: 'addItemClass'},
                            {type: 'doc', id: 'systemFunctions/item/addItemPeriod', label: 'addItemPeriod'},
                            {type: 'doc', id: 'systemFunctions/item/addItemUnit', label: 'addItemUnit'},
                            {type: 'doc', id: 'systemFunctions/item/deleteItem', label: 'deleteItem'},
                            {type: 'doc', id: 'systemFunctions/item/deleteItemAssetRate', label: 'deleteItemAssetRate'},
                            {type: 'doc', id: 'systemFunctions/item/deleteItemAssetRates', label: 'deleteItemAssetRates'},
                            {type: 'doc', id: 'systemFunctions/item/deleteItemAttribute', label: 'deleteItemAttribute'},
                            {type: 'doc', id: 'systemFunctions/item/deleteItemClass', label: 'deleteItemClass'},
                            {type: 'doc', id: 'systemFunctions/item/deleteItemPeriod', label: 'deleteItemPeriod'},
                            {type: 'doc', id: 'systemFunctions/item/deleteItemUnit', label: 'deleteItemUnit'},
                            {type: 'doc', id: 'systemFunctions/item/getAssetItems', label: 'getAssetItems'},
                            {type: 'doc', id: 'systemFunctions/item/getItemAttributes', label: 'getItemAttributes'},
                            {type: 'doc', id: 'systemFunctions/item/getItemClasses', label: 'getItemClasses'},
                            {type: 'doc', id: 'systemFunctions/item/getItemPeriod', label: 'getItemPeriod'},
                            {type: 'doc', id: 'systemFunctions/item/getItemPeriods', label: 'getItemPeriods'},
                            {type: 'doc', id: 'systemFunctions/item/getItems', label: 'getItems'},
                            {type: 'doc', id: 'systemFunctions/item/getItemSource', label: 'getItemSource'},
                            {type: 'doc', id: 'systemFunctions/item/getItemUnit', label: 'getItemUnit'},
                            {type: 'doc', id: 'systemFunctions/item/getItemUnits', label: 'getItemUnits'},
                            {type: 'doc', id: 'systemFunctions/item/updateItem', label: 'updateItem'},
                            {type: 'doc', id: 'systemFunctions/item/updateItemAssetRate', label: 'updateItemAssetRate'},
                            {type: 'doc', id: 'systemFunctions/item/updateItemAttribute', label: 'updateItemAttribute'},
                            {type: 'doc', id: 'systemFunctions/item/updateItemClass', label: 'updateItemClass'},
                            {type: 'doc', id: 'systemFunctions/item/updateItemField', label: 'updateItemField'},
                            {type: 'doc', id: 'systemFunctions/item/updateItemPeriod', label: 'updateItemPeriod'},
                       ]
            },
            {type: 'category', label: 'system.kanoa.lot', link: {type: 'doc', id: 'systemFunctions/apiLotIntro'},
                items: [
                            {type: 'doc', id: 'systemFunctions/lot/addLot', label: 'addLot'},
                            {type: 'doc', id: 'systemFunctions/lot/addLotEvent', label: 'addLotEvent'},
                            {type: 'doc', id: 'systemFunctions/lot/addLotStateReason', label: 'addLotStateReason'},
                            {type: 'doc', id: 'systemFunctions/lot/deleteLot', label: 'deleteLot'},
                            {type: 'doc', id: 'systemFunctions/lot/deleteLotEvent', label: 'deleteLotEvent'},
                            {type: 'doc', id: 'systemFunctions/lot/deleteLotStateReason', label: 'deleteLotStateReason'},
                            {type: 'doc', id: 'systemFunctions/lot/enableAssetLotStateLink', label: 'enableAssetLotStateLink'},
                            {type: 'doc', id: 'systemFunctions/lot/getAssetLotStateReasons', label: 'getAssetLotStateReasons'},
                            {type: 'doc', id: 'systemFunctions/lot/getLotEvents', label: 'getLotEvents'},
                            {type: 'doc', id: 'systemFunctions/lot/getLotQty', label: 'getLotQty'},
                            {type: 'doc', id: 'systemFunctions/lot/getLots', label: 'getLots'},
                            {type: 'doc', id: 'systemFunctions/lot/getLotStateReasons', label: 'getLotStateReasons'},
                            {type: 'doc', id: 'systemFunctions/lot/getLotStates', label: 'getLotStates'},
                            {type: 'doc', id: 'systemFunctions/lot/getNextLotName', label: 'getNextLotName'},
                            {type: 'doc', id: 'systemFunctions/lot/linkAssetLotStates', label: 'linkAssetLotStates'},
                            {type: 'doc', id: 'systemFunctions/lot/unlinkAssetLotState', label: 'unlinkAssetLotState'},
                            {type: 'doc', id: 'systemFunctions/lot/updateLot', label: 'updateLot'},
                            {type: 'doc', id: 'systemFunctions/lot/updateLotEvent', label: 'updateLotEvent'},
                            {type: 'doc', id: 'systemFunctions/lot/updateLotStateReason', label: 'updateLotStateReason'},
                            {type: 'doc', id: 'systemFunctions/lot/updateLotStateReasonField', label: 'updateLotStateReasonField'},
                       ]
            },
            {type: 'category', label: 'system.kanoa.order', items: [{type: 'autogenerated', dirName: 'systemFunctions/order'}]},
            {type: 'category', label: 'system.kanoa.quality', items: [{type: 'autogenerated', dirName: 'systemFunctions/quality'}]},
            {type: 'category', label: 'system.kanoa.schedule', items: [{type: 'autogenerated', dirName: 'systemFunctions/schedule'}]},
            {type: 'category', label: 'system.kanoa.security', items: [{type: 'autogenerated', dirName: 'systemFunctions/security'}]},
            {type: 'category', label: 'system.kanoa.shift', items: [{type: 'autogenerated', dirName: 'systemFunctions/shift'}]},
            {type: 'category', label: 'system.kanoa.utilities', items: [{type: 'autogenerated', dirName: 'systemFunctions/utilities'}]},
        ]
    },
  ],
};
module.exports = sidebars;





/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
//const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
//    tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
/*  
  tutorialSidebar: [
    'welcome'
  ]
};
*/
/*
module.exports = {
  mySidebar: [
    {
      type: 'category',
      label: 'Getting Started',
      items: [
        {
          type: 'doc',
          id: 'new folder structure/kanoa-mes/architecture',
        },
      ],
    },
    {
      type: 'category',
      label: 'Docusaurus',
      items: [
        {
          type: 'doc',
          id: 'new folder structure/kanoa-mes/architecture',
        },
        {
          type: 'doc',
          id: 'new folder structure/kanoa-mes/architecture',
        },
      ],
    },
    {
      type: 'link',
      label: 'Learn more',
      href: 'https://example.com',
    },
  ],
};
*/

//};
//module.exports = sidebars;
