/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
    tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
/*  
  tutorialSidebar: [
    'new folder structure/kanoa-mes/architecture',
    'welcome',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['welcome'],
    },
  ],
*/
/*
module.exports = {
  mySidebar: [
    {
      type: 'category',
      label: 'Getting Started',
      items: [
        {
          type: 'doc',
          id: 'new folder structure/kanoa-mes/architecture',
        },
      ],
    },
    {
      type: 'category',
      label: 'Docusaurus',
      items: [
        {
          type: 'doc',
          id: 'new folder structure/kanoa-mes/architecture',
        },
        {
          type: 'doc',
          id: 'new folder structure/kanoa-mes/architecture',
        },
      ],
    },
    {
      type: 'link',
      label: 'Learn more',
      href: 'https://example.com',
    },
  ],
};
*/

};
module.exports = sidebars;
