/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check


/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
//    tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually

  tutorialSidebar: [
    'welcome',
    'architecture',
    {
        type: 'category',
        label: 'Getting Started',
        link: {type: 'doc', id: 'gettingStarted/main'},
        items: [
                'gettingStarted/system-requirements',
                'gettingStarted/installation',
                {
                    type: 'category', 
                    label: 'Configuration',
                    link: {type: 'doc', id: 'gettingStarted/configuration'},
                    items: [{type: 'autogenerated', dirName: 'configuration'},],
//                    items: ['configuration/users', 'configuration/assets', 'configuration/materials', 'configuration/modes', 'configuration/states'],
                },
        ],
    },
//    {type: 'link', label: 'KanoaOPS', href: 'https://kanoa.ai/kanoa-ops'},

    {
        type: 'category',
        label: 'Operations Management',
        link: {type: 'doc', id: 'kanoa-ops'},
        items: [{type: 'autogenerated', dirName: 'kanoa-ops'},],
    },
    {
        type: 'category',
        label: 'Quality Management',
        link: {type: 'doc', id: 'kanoa-quality'},
        items: [{type: 'autogenerated', dirName: 'kanoa-quality'},],
    },

    {
        type: 'category',
        label: 'Appendix',
        link: {type: 'doc', id: 'APPENDIX/api-intro'},
        items: [{type: 'autogenerated', dirName: 'APPENDIX/System Functions/system.kanoa'},],
    },
  ],
};
module.exports = sidebars;





/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
//const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
//    tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
/*  
  tutorialSidebar: [
    'welcome'
  ]
};
*/
/*
module.exports = {
  mySidebar: [
    {
      type: 'category',
      label: 'Getting Started',
      items: [
        {
          type: 'doc',
          id: 'new folder structure/kanoa-mes/architecture',
        },
      ],
    },
    {
      type: 'category',
      label: 'Docusaurus',
      items: [
        {
          type: 'doc',
          id: 'new folder structure/kanoa-mes/architecture',
        },
        {
          type: 'doc',
          id: 'new folder structure/kanoa-mes/architecture',
        },
      ],
    },
    {
      type: 'link',
      label: 'Learn more',
      href: 'https://example.com',
    },
  ],
};
*/

//};
//module.exports = sidebars;
